SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE ChiTietSanPham;
TRUNCATE TABLE HoaDon;
TRUNCATE TABLE PhongDaDat;
TRUNCATE TABLE BangLuong;
TRUNCATE TABLE ThuongPhat;
TRUNCATE TABLE PhanCa;
TRUNCATE TABLE Phong;
TRUNCATE TABLE SanPham;
TRUNCATE TABLE KhachHang;
TRUNCATE TABLE NhanVien;
TRUNCATE TABLE LoaiPhong;
TRUNCATE TABLE CaLamViec;
TRUNCATE TABLE MucLuong;
TRUNCATE TABLE PhieuChi;

SET FOREIGN_KEY_CHECKS = 1;